version: '3.4'
services:
  photon:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    image: jfelectron/geocoder
    volumes:
      - data:/photon/photon_data
    ports:
      - 2322:2322

volumes:
  data:
    driver: local
